<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CentrosIntegrales.Billing.Application\CentrosIntegrales.Billing.Application.csproj" />
    <ProjectReference Include="..\CentrosIntegrales.Billing.Domain\CentrosIntegrales.Billing.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
