services:
  - type: web
    name: centros-integrales-ride
    env: docker
    plan: free
    region: ohio
    rootDir: services/electronic-billing
    dockerfilePath: services/electronic-billing/Dockerfile
    dockerContext: services/electronic-billing
    healthCheckPath: /health
    envVars:
      - key: RIDE_SERVICE_API_KEY
        sync: false
