<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CentrosIntegrales.Billing.Application\CentrosIntegrales.Billing.Application.csproj" />
    <ProjectReference Include="..\CentrosIntegrales.Billing.Infrastructure\CentrosIntegrales.Billing.Infrastructure.csproj" />
  </ItemGroup>

</Project>
